# Generated by Django 4.2.6 on 2024-01-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_has_discount_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='brands'),
        ),
        migrations.AddField(
            model_name='product',
            name='adding_to_basket_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
