# Generated by Django 4.2.6 on 2023-11-15 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazarlar',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='başlıq')),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='blogs')),
                ('author', models.ForeignKey(help_text='Bloqun yazarini seçin', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='core.author', verbose_name='yazar')),
            ],
            options={
                'verbose_name': 'Bloq',
                'verbose_name_plural': 'Bloqlar',
            },
        ),
    ]
